#index:
#  path: /
#  controller: App\Controller\DefaultController::index

index:
  path: /
  defaults: {_controller: 'App\Controller\IriniController::index'}

app_logout:
  path: /logout
  methods: GET
